### ISSUE TITLE
User Logging

### ISSUE THREAD

**Issue by meghanhorton** [CU-WebTech/printmaster#12]
Would it be possible to log the use of the tool and image generation? Possibly store the images.

Case: An image gets sent out, nobody knows who created it, it looks terrible, the person who created it needs to be talked to.

**Comment by appalcich** [comment]
There are tools in the ut framework that can do this if you want to blend languages.

**Comment by ezmac** [comment]
I don't want to add coldfusion to a ruby app.  I'll add an optional feature that will post the image data to an endpoint when someone generates an image.  With our server setup, the request will have associated user info and can log the generated image and user.

**Comment by appalcich** [comment]
Tad and I talked. We decided that we'll make an API for the logging tool, add a log_extra_data column to the log table, then memegenerator will call the API and send the base64 image data which will be stored in the logging system. In this way, we'll be able to add a screen to the apps admin where we can see the images created with the tool.

**Comment by ezmac** [comment]
has options to track user usage via external logging api and through capturing raw image and parameters used to generate image.
