### ISSUE TITLE
Default font style

### ISSUE THREAD

**Issue by meghanhorton** [CU-WebTech/printmaster#13]
The text style on load is defaulting to a basic sans-serif instead of the Freight Text font. As soon as you press any button on the sidebar, it switches the font to what it should be.

![Default Text](https://cloud.githubusercontent.com/assets/6876713/11103174/d92c81e8-888e-11e5-81ef-77fcf8c9ad0f.png)

**Comment by meghanhorton** [comment]
This may be a fluke. I restarted the server and ran it this morning and it seems fine.

**Comment by ezmac** [comment]
it's no fluke, but it's now fixt.  Added MEME.render() to typekit's loaded callback so it will always re-render once fonts are loaded.
