### ISSUE TITLE
Linebreaks

### ISSUE THREAD

**Issue by meghanhorton** [CU-WebTech/printmaster#15]
So, linebreaks _are_ important.

**Comment by ezmac** [comment]
fixed linebreaks.

**Comment by meghanhorton** [comment]
I don't think this is fixed, unless we weren't talking about the same thing. 

Carriage returns = do not work. :(

**Comment by ezmac** [comment]
Misunderstanding about line breaks.  I was considering the feature of using \n to insert a line break.  That still works.  Line breaks also now work.
