### ISSUE TITLE
Chrome bug - jumps to end of text

### ISSUE THREAD

**Issue by meghanhorton** [CU-WebTech/printmaster#17]
When adding characters to existing text, it jumps to the end.

<img width="308" alt="screen shot 2015-11-13 at 11 57 06 am" src="https://cloud.githubusercontent.com/assets/6876713/11151938/d990f6bc-89fd-11e5-9a8e-3bb44a4f9167.png">

**Comment by ezmac** [comment]
not sure why it's isolated to chrome but the MemeEditor view is listening to the model's change event and on every keypress, the value in the input is set on the model; this triggers a model change event and the MemeEditor is re-rendered.  That re-render makes the cursor jump to the end of the input.

**Comment by ezmac** [comment]
The two way binding wasn't really that important.  instead, MemeEditor now hooks on the model's load event.
