### ISSUE TITLE
Layouts

### ISSUE THREAD

**Issue by meghanhorton** [CU-WebTech/printmaster#2]
### Layout Options should include:
* Background Color Only (default) _as is_
* Image background _as is_
* Left/Right _as is_
* **New** side-by-side icons (25% icon, 75% text)
![side-by-side](https://cloud.githubusercontent.com/assets/6876713/10943144/326746ca-82e1-11e5-9269-cf212d0ebbb0.png)

### Icon samples, in white
_Note: These are SVGs. If you would prefer PNGs, just let me know._
[Mic Icon](http://media.univcomm.cornell.edu/icons/quotes/mic_icon.svg)
[Sound Icon](http://media.univcomm.cornell.edu/icons/quotes/sound_icon.svg)

**Comment by ezmac** [comment]
For clarification, should these icons be considered "watermarks" that sit on the left or should we consider them to be new iconography specifically for the side by side layout?

**Comment by meghanhorton** [comment]
These are new icons, specifically for the side-by-side layout. There will be 4-6 to choose from in the layout options. They have the capability of being paired with the insignia.

Also - these icons are available in a font icon set - so if that would be easier than dealing with SVGs, we can do that instead.

**Comment by ezmac** [comment]
do you want text centering or right alignment while using the icon layout?

**Comment by meghanhorton** [comment]
Left only :)

**Comment by ezmac** [comment]
For right now, there's no lockout to keep anyone from using right/center align with icon layout.  It'll look janky, though, so they'll learn not to use the combo in the short term.
That code is committed and pushed, so I'll close this and track the other as an enhancement.

To be tracked in 
https://github.com/CU-WebTech/printmaster/issues/22
