### ISSUE TITLE
Logo Options

### ISSUE THREAD

**Issue by meghanhorton** [CU-WebTech/printmaster#3]
### Update logo options
* Add option for "No Logo"
* Set the Logo sizes to be an 45px, instead of percentage
* Switch out logos with the following

### Logos
[Cornell Logo - Black](http://cornell.edu/assets/core/images/logo-black.svg)
[Cornell Logo - White](http://cornell.edu/assets/core/images/logo-white.svg)

**Comment by ezmac** [comment]
Made logos configurable in settings file.
