### ISSUE TITLE
Add secondary attribution line

### ISSUE THREAD

**Issue by meghanhorton** [CU-WebTech/printmaster#6]
### Add an extra line of attribution for "Organization" or "Title"
* Can just be labeled "Attribution Line 1" and "Attribution Line 2" or something
* No text-styling is needed, just use the Freight Sans font, not bold, same size as the first line

**Similar To**
![NYTimes](https://pbs.twimg.com/media/CS-JmJiWwAAb-d2.png:large)

**Comment by ezmac** [comment]
there's now a subcredit field in the editor and settings file.  You can adjust font and size, but it does take the allcaps setting from the main credit.  Acceptable or does it need it's own allcaps setting?

**Comment by meghanhorton** [comment]
That works for me. If somebody wants part of it to be all caps and can't change it, they can turn on capslock :)
