### ISSUE TITLE
Alignment of text

### ISSUE THREAD

**Issue by meghanhorton** [CU-WebTech/printmaster#7]
Vertical "Align Middle" of text doesn't work properly.

![Yuck!](https://cloud.githubusercontent.com/assets/6876713/10943942/c020b368-82e4-11e5-80d1-c1559b254aff.png)

**Comment by ezmac** [comment]
Added a bit of code to estimate the text width/height with a standard div.  This breaks a little with bold/italics and probably with newlines.
