### ISSUE TITLE
Text Edge Bugs

### ISSUE THREAD

**Issue by meghanhorton** [CU-WebTech/printmaster#8]
I don't think these are SUPER important bugs, they can be visually adjusted, but they're a little annoying.

### Text disappears after a certain point, after resizing text
![Where'd it go?](https://cloud.githubusercontent.com/assets/6876713/10944017/1579feb4-82e5-11e5-8f33-2db9b889ef3c.png)

### Long words run off the edge
![You're giving me a bad wrap](https://cloud.githubusercontent.com/assets/6876713/10944034/29acb9ee-82e5-11e5-8a1c-665dabf613dd.png)

**Comment by ezmac** [comment]
Long words should now wrap better.
