### ISSUE TITLE
Gallery of "Recently Created"

### ISSUE THREAD

**Issue by meghanhorton** [CU-WebTech/printmaster#9]
I'm putting this in here, even though we discussed that it was not necessary. 

The ability to show recently created images as thumbs to prevent duplication.

**Comment by ezmac** [comment]
Recently created memes (assuming there's a backend) will be displayed.  Still need to remove the previously generated version.

**Comment by ezmac** [comment]
Gallery of recently created was removed by request.  Code to enable it has been left in.
